In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Mathematic Operation Using Numpy

In [1]:
import numpy as np 

In [4]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Addition 


In [10]:
# Addition of two matrix 

arr1 + arr2 


array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [9]:
# we also yse  a function to add two matrix 

np.add(arr1,arr2 )

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

# Substraction 


In [11]:
# substract one matrix to an other matrix

arr1-arr2 # normal formate 

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [12]:
# functions for substraction

np.subtract(arr1,arr2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# Divide

In [13]:
# Divide one matrix to one other matrix 
arr1/arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
# divide function
np.divide(arr1,arr2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# Multiplication

In [18]:
# multiplication from one elemnet to an other element

arr1*arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [19]:
# multiplication function

np.multiply(arr1,arr2) # here are the simplemultiplication from one element to an other element 

# for matrix multiplication we have to use @ function

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [20]:
arr1@arr2 # this is the real matrix function multiplication 

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [21]:
# function

arr1.dot(arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [23]:
arr1
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Maximum value 

To find the maximum value of the matrix 

In [24]:
# maximum value finding  function

arr1.max()

9

In [25]:
arr1.argmax() # index finding 

8

In [45]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr1.max(axis = 0) # in the max function 0 stands for row  

array([7, 8, 9])

In [27]:
arr1.max(axis = 1) # in the max function 1 stands for column  

array([3, 6, 9])

# Minimum  

To find minimum function of the matrix 

In [28]:
arr1.min()

1

In [29]:
arr1.argmin() # index 

0

In [44]:
arr1


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr1.min(axis = 0 ) # minimum value of the particular axis zero represent row

array([1, 2, 3])

In [31]:
arr1.min(axis = 1 ) # minimum value of the particular axis one  represent column  

array([1, 4, 7])

In [32]:
# yek particular matrix to add karne ka function

np.sum(arr1)

45

In [33]:
np.sum(arr2)

45

In [37]:
# sum of every column
np.sum(arr1,axis = 0) # for the sum function zero stands  for the column and 1 stands for the row a

array([12, 15, 18])

In [35]:
arr1
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Mean

In [38]:
# avverage of the matrix function 

np.mean(arr1)

5.0

# square root 

In [39]:
# square root of the particular function

np.sqrt(arr1) # the square root of every numbers 

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

# Standard D

In [40]:
# standard division of the the matrix 

np.std(arr1)

2.581988897471611

In [41]:
# exponent of every matrix

np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

# Log

In [42]:
# log of every matrix

np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [43]:
# find matrix log base 10 value
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])