In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [4]:
import numpy as np 

x = np.array([1,2,3,4]) #array are basically print without commas 
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
y = [1,2,3,4] # list are print with commas 
print(y)
print(type(y))


[1, 2, 3, 4]
<class 'list'>


# CHECKING TIMING OF ARRAY AND NUMPY 

In [7]:
%timeit [j**4 for j in range(1,9)] # isme humne list ki timing check ki hai 

2.63 µs ± 24 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [11]:
import numpy as np

%timeit np.arange(1,9)**4 # isme humne list ki timing checki hai 


2.43 µs ± 24.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# HOW TO CREATE A ARRAY IN NUMPY

1 Numpy ke andar hum array kais create kar sakte hai

2 Numpy ke andar hum multi dimensional array kaise bana sakte hai


In [14]:
import numpy as np


In [22]:
# create a numpy array with variable the variable is x
x = [1,2,3] # this list is converted in to array
y = np.array(x)
print(y)


[1 2 3]


In [26]:
# create a numpy array without variable and taking directly list
x = [1,2,3] # this list is converted in to array
y = np.array([1,2,3,4])
y # for checking the type 
print(type(y)) # this method is also use to check the type 
print(y)


<class 'numpy.ndarray'>
[1 2 3 4]


In [29]:
# in that fuction we use input function and make array 
l =[] #from list function to array 
for i in range(1,5):
    int_1 = int(input("Enter :")) # if we use the input without int function then the output is string and if we use int then out put is normal 
    l.append(int_1) # append function is use to insert the value 
print(np.array(l))



Enter : 23
Enter : 45
Enter : 24
Enter : 2


[23 45 24  2]


# Types of array 
1-D Array,[1,2,3]

2-D Array,[[1,2,3]]

3-D Array,[[[1,2,3]]]

Higher Dimensional Array

ndim function is use to find the dimension of array 

In [36]:
# 1-D Array

x = [1,2,3,4]
y = np.array([1,2,3,4])

print(y)
print(type(y))
print(y.ndim) #this is showing the dimension of array 

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [42]:
# 2-D Array

a = [[1,2,3,4,5]] # 2 bracket is there 
b = np.array([[1,2,3,4],[1,2,3,4]])

print(b)
print(type(b))
print(b.ndim)


[[1 2 3 4]
 [1 2 3 4]]
<class 'numpy.ndarray'>
2


In [48]:
# 3-D Array

a = [[[1,2,3,4,5]]] # 3 bracket is there 
b = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])

print(b)
print(type(b))
print(b.ndim)


[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
<class 'numpy.ndarray'>
3


In [57]:
# multii diamensional array 
arn = np.array([1,2,3,4],ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10
