In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Numpy Array Concatination and Split 

In [2]:
# is function me hum deakhenge ki hum array ko kaise join karte hai aur particular array ko kaise split karte hai 

In [8]:
import numpy as np 

Humne yaha yek rendom data ko generate kiya hai 

In [9]:
ar_1 = np.arange(1,17).reshape(4,4) #humne isme reshape condition laga ke matrix generate kiya hai 
print(ar_1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [10]:
ar_2 = np.arange(17,33).reshape(4,4) #humne isme reshape condition laga ke matrix generate kiya hai 
print(ar_2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


# Concatenate

first array ko hum second array ke sath hum conctinate karenge 

Means first array ke just nechey second array ayega 

Humko yaha par add nahi karna hai yaha par dono arrays ko jaoin karna hai 

# column wise concatenation 

In [11]:
# yaha par donoarray ko hum concatenate karenge with the help of this function

np.concatenate((ar_1,ar_2)) #  concatenate karne ke liye humko do braket lagana padta hai 

# ye humne coloumn wise concatenation kiya hai 
# means first array ka columnn dusre array ke column me add ho gaya hai

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

# Row wise concatenation 

In [12]:
print(ar_1)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [13]:
print(ar_2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [16]:
# yaha par donoarray ko hum concatenate karenge with the help of this function

np.concatenate((ar_1,ar_2),axis = 1) #  concatenate karne ke liye humko do braket lagana padta hai and uske sath axis bhi define karna padta hai for rows concatenation  

# ye humne Row wise concatenation kiya hai 
# means first array ka Row dusre array ke Row me add ho gaya hai

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [18]:
# A Shortcut method of column wise concatenation 

np.vstack((ar_1,ar_2)) #yaha par bhi humko tupple ka use karna padega mens double bracket


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [19]:
# A Shortcut method of Row wise concatenation 

np.hstack((ar_1,ar_2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

# Split

Array function ko break karne ke liye hum split function ka use karte hai 


In [26]:
# array ko split karne ka functio

np.split(ar_1,2) # comma 2 means ki humko particular array kitne part me divide karna hai 

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [12]:
# for checking the variable types 
list = np.split(ar_1,2)
print(type(list))

<class 'list'>


In [36]:
list [0]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [37]:
print(type(list [0]))

<class 'numpy.ndarray'>


In [ ]:
# split function array ko split karta hai but jo splited array hai wo list me store hota hai


In [13]:
# Array spit column wise
np.split(ar_1,2,axis = 1 ) 

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]