In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Random Sampilling With Numpy

if the acurate data is note avaliable then we use the Random Sampilling 

In [1]:
import numpy as np 

In [2]:
# we import random model for made the random values 

import random 

# random.random 

this function gives the random value less then 0 

In [8]:
# now generate the random values

np.random.random(1) # agar humko 0-1 ke beech me random value chaiye to hum "random.random" lekhenge 
                    # but aagar 1 se uppar chaiye to hum "random.randint" ka use karenge 

array([0.43165827])

In [10]:
 2 D Array 3*3

np.random.random((3,3))

# here the random function is call and the 2 D array is created 3*3

array([[0.59193321, 0.22315079, 0.41904501],
       [0.89629961, 0.36681011, 0.15010939],
       [0.6532507 , 0.77590912, 0.52431797]])

In [15]:
# 2 D Array 2*2

np.random.random((2,2))

array([[0.75139827, 0.63428504],
       [0.24117853, 0.56161426]])

# random.randint()

this function use to give the integer value 
means give grater then 0 value 

In [4]:
# for integer number mens greater then 1

np.random.randint(1,4) # this function use for normal random numbers 1 D 

2

In [6]:
# if we want random matrix grayer then zero then we use this function

np.random.randint(1,4,(4,4))

# Here the random matrix generated  2 D Array 


array([[3, 3, 1, 2],
       [3, 3, 1, 2],
       [2, 2, 2, 3],
       [1, 3, 1, 2]])

In [7]:
np.random.randint(1,4,(2,4,4))

# 3 D Array is generated with the help of this function 

array([[[1, 2, 1, 2],
        [3, 3, 2, 1],
        [2, 3, 1, 2],
        [3, 2, 3, 1]],

       [[1, 3, 3, 1],
        [2, 2, 2, 2],
        [3, 2, 3, 2],
        [3, 1, 2, 1]]])

# random.seed()

seed function give the same out put same as previous function 

In [8]:
# when we use the random function the value are continuously change in every out put

# if we want same out put same as previous function then we use this type of function

np.random.seed(10)
np.random.randint(1,4,(2,4,4))


array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [9]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))


array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [10]:
# both the 3 D array is same 

# random.rand 

this funcyion is use to create a random 1 D array

and there value is less then 0 

In [12]:
np.random.rand(3)

array([0.58390137, 0.18263144, 0.82608225])

In [13]:
np.random.rand(3,3)

array([[0.10540183, 0.28357668, 0.06556327],
       [0.05644419, 0.76545582, 0.01178803],
       [0.61194334, 0.33188226, 0.55964837]])

# random.randn

this function gives the random value in negative 

In [14]:
np.random.randn(3,3)

array([[-0.94245806, -1.74554298, -1.02094527],
       [-0.16206903, -0.6579709 ,  0.42211306],
       [ 0.62402334,  0.5016401 ,  0.84143473]])

In [15]:
# if list se random number ko out karna hai to hum "choice" function ka use karte hai

l = [1,2,3,4,5]
np.random.choice(l)

3

In [17]:
l = [1,2,3,4,5]
np.random.choice(l) # this function gives us the random value from the list 

1

In [18]:
# for function ka use karke hum check karenge aur ye humko alaag function output me dega 

for i in range(20):
    print(np.random.choice(l))

# ye humko 20 alag alag numbers dega
    

3
4
1
5
5
1
2
2
5
1
3
2
4
2
3
1
2
2
1
3


# Permutation 

random number se hum usko permutate kar sakte hai

In [20]:
l 

[1, 2, 3, 4, 5]

In [21]:
np.random.permutation(l)

array([5, 3, 1, 2, 4])

In [22]:
np.random.permutation(l)

array([4, 2, 5, 1, 3])